version: '3.3'
services:
  pptp:
    env_file: .env
    image: mmontagna/docker-vpn-pptp:latest
    container_name: pptp
    privileged: true
    restart: always
    network_mode: host
    environment:
      - client=${PPTP_USER_LIST}

  l2tp:
    env_file: .env
    image: fcojean/l2tp-ipsec-vpn-server:latest
    container_name: l2tp
    privileged: true
    restart: always
    ports:
      - 510:500/udp
      - 4510:4500/udp
    volumes:
      - /lib/modules:/lib/modules:ro
    environment:
      - VPN_IPSEC_PSK=${L2TP_IPSEC_PSK}
      - VPN_USER_CREDENTIAL_LIST=${L2TP_USER_LIST}

  openconnect:
    env_file: .env
    image: quay.io/aminvakil/ocserv:latest
    container_name: openconnect
    restart: always
    privileged: true
    ports:
      - ${OPENCONNECT_PORT}:443
      - ${OPENCONNECT_PORT}:443/udp
    environment:
      - CA_CN=${OPENCONNECT_CA_CN}
      - CA_ORG=${OPENCONNECT_CA_ORG}
      - CA_DAYS=${OPENCONNECT_CA_DAYS}
      - SRV_CN=${OPENCONNECT_SRV_CN}
      - SRV_ORG=${OPENCONNECT_SRV_ORG}
      - SRV_DAYS=${OPENCONNECT_SRV_DAYS}
      - NO_TEST_USER=${OPENCONNECT_NO_TEST_USER}

  mtproto:
    env_file: .env
    image: telegrammessenger/proxy:latest
    container_name: mtproto
    restart: always
    ports:
      - ${MTPROTO_PORT}:443
    environment:
      - SECRET_COUNT=${MTPROTO_SECRET_COUNT}
      - SECRET=${MTPROTO_SECRET}

  sstp:
    env_file: .env
    image: fernandezcuesta/softethervpn:latest
    container_name: sstp
    restart: always
    ports:
      - ${SSTP_L2TP_PORT_500}:500/udp
      - ${SSTP_L2TP_PORT_4500}:4500/udp
      - ${SSTP_L2TP_PORT_1701}:1701/tcp
      - ${SSTP_OPENVPN_PORT}:1194/udp
      - ${SSTP_PORT}:443/tcp
    environment:
      - PSK=${L2TP_IPSEC_PSK}
      - USERNAME=milad
      - PASSWORD=P@SSWORD
      - SERVER_PWD=P@SSWORD
      - OPENVPN_ENABLED=true
      - SSTP_ENABLED=true
      - CERT=/tmp/cert.pem
      - KEY=/tmp/key.pem

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=auto #optional
      - SERVERPORT=51820 #optional
      - PEERS=10 #optional
      - PEERDNS=8.8.8.8 #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - /opt/wireguard-server/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  shadowsocks:
    image: shadowsocks/shadowsocks-libev:latest
    container_name: shadow_socks
    restart: always
    ports:
      - "8888:8388/tcp"
      - "8888:8388/udp"
    environment:
      - PASSWORD=P@SSWORD
      - METHOD=chacha20-ietf-poly1305
      - DNS_ADDRS=1.1.1.1,8.8.8.8

  proxy:
    image: datadog/squid
    container_name: proxy_squid
    ports:
      - "8181:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./passwords:/etc/squid/passwords
    restart: always

  mikrotik:
    image: evilfreelancer/docker-routeros:6.46.5
    container_name: mikrotik
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "22280:80"
      - "28080:8080"
      - "22221:21"
      - "22222:22"
      - "22223:23"
      - "22443:443"
      - "21705:1701"
      - "21725:1723"
      - "21726:1194/tcp"
      - "21727:1194/udp"
      - "21812:1812/udp"
      - "21813:1813/udp"
      - "24500:4500/udp"
      - "22250:50"
      - "22251:51"
      - "22500:500/udp"
      - "22021:2021"
      - "22022:2022"
      - "22023:2023"
      - "22027:2027"
      - "25900:5900"
      - "28291:8291"
      - "28728:8728"
      - "28729:8729"
      - "28900:8900"

  dns_proxy:
    env_file: .env
    cap_add:
      - NET_ADMIN
    container_name: dns_proxy
    ports:
      - "53:53/udp"
    environment:
      - IP=PublicIpOfContainer
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ulimits:
      nofile:
        soft: 1024000
        hard: 1024000
   v2ray:
      image: ghcr.io/miladrahimi/v2ray:latest
      container_name: v2ray_upstream
      restart: always
      command: [ "v2ray", "-config=/etc/v2ray/config.json" ]
      ports:
        - ${VMESS_PORT:-1013}:1013
      volumes:
        - ./config/:/etc/v2ray/
        - ./logs:/var/log/v2ray/

        https://github.com/straxico/v/blob/main/Readme.md 